/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marvellous.packer.unpacker;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

class InvalidFileException extends Exception
{
    public InvalidFileException(String str)
    {
        super(str);
    }
}
public class MarvellousUnpackFront extends Template implements ActionListener
{
    JButton SUBMIT,PREVIOUS;
    JLabel label1,label2,title;
    final JTextField text1;
    
    public MarvellousUnpackFront() 
    {
        //initComponents();
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        title = new JLabel("Marvellous Unpacking Portal");
        Dimension size = title.getPreferredSize();
        title.setBounds(40,50,size.width + 60,size.height);
        title.setFont(new Font("Century",Font.BOLD,17));
        title.setForeground(Color.blue);
        
        label1 = new JLabel();
        label1.setText("File Name: ");
        label1.setForeground(Color.white);
        label1.setBounds(350,50,size.width,size.height);
        
        text1=new JTextField(15);
        Dimension tsize=text1.getPreferredSize();
        text1.setBounds(500,50,tsize.width,tsize.height);
        text1.setToolTipText("Enter Name Of Directory");
        
        SUBMIT = new JButton("Extract here");
        Dimension bsize= SUBMIT.getPreferredSize();
        SUBMIT.setBounds(500,100,bsize.width,bsize.height);
        SUBMIT.addActionListener(this);
        
        PREVIOUS = new JButton("PREVIOUS");
        Dimension b2size= PREVIOUS.getPreferredSize();
        PREVIOUS.setBounds(500,100,b2size.width,b2size.height);
        PREVIOUS.addActionListener(this);
        
        _header.add(title);
        _content.add(label1);
        
        _content.add(text1);
        
        _content.add(SUBMIT);
        _content.add(PREVIOUS);
        
        this.setSize(1000,400);
        this.setResizable(false);
        this.setVisible(true);
        text1.requestFocusInWindow();     
    }
    
    public void actionPerformed(ActionEvent ae)
    {
        if(ae.getSource() == exit)
        {
            this.setVisible(false);
            System.exit(0);
        }
        if(ae.getSource() == minimize)
        {
            this.setState(this.ICONIFIED);
        }

        if(ae.getSource() == SUBMIT)
        {
            try
            {
                MarvellousUnpack obj = new MarvellousUnpack(text1.getText());
                this.dispose();
                NextPage t= new NextPage("admin");
            }
            catch(InvalidFileException obj)
            { 
                this.setVisible(false);
                this.dispose();
                
                JOptionPane.showMessageDialog(this, "Invalid paked file","Error",JOptionPane.ERROR_MESSAGE);
                NextPage t = new NextPage("admin");
            }
            catch(Exception e)
            {
                
            }
        }    
             if(ae.getSource() == PREVIOUS)
            {
                this.setVisible(false);
                this.dispose();
                NextPage t= new NextPage("admin");
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarvellousUnpackFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarvellousUnpackFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarvellousUnpackFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarvellousUnpackFront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarvellousUnpackFront().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
